### ISSUE TITLE
[Bug] on mac standalone version, dragging toolbar window leads to white screen

### ISSUE THREAD

**Issue by iceboundflame** [cheton/cnc#52] opened 2016-06-28 02:49 UTC
Attempting to drag the G-Code tool window out of the right sidebar leads to a white screen. Dev tools reports an error:
![screen shot 2016-06-27 at 7 48 50 pm](https://cloud.githubusercontent.com/assets/933687/16402300/42a882be-3ca0-11e6-925d-a4f9d93aa77d.png)

v1.3.2 on mac

**Comment by cheton** [comment] 2016-06-28 03:30
I fixed a lot of drag and drop issues recently. It will be fixed in the release.

**Comment by iceboundflame** [comment] 2016-06-28 06:43
Thanks! Good to hear.

**Comment by iceboundflame** [comment] 2016-07-01 05:28
FYI I built the latest build into a Mac OS X app and it still has this issue; I can move every panel except the Axes one. Also, if I collapse the Axes panel, then I can move it.

It just goes white screen and disconnects the dev tools without any error recorded. When I connected to the Mac app in Chrome (localhost:65008) it also crashed when dragging this panel - with an "Aw, snap" error (no JS error visible).

**Comment by cheton** [comment] 2016-07-01 06:22
It worked several days ago, but now I can reproduce this issue for both the web-based UI and Mac app.  The error seems very strange, I will try to figure out what's going wrong.

**Comment by cheton** [comment] 2016-07-01 10:31
This issue is related to https://github.com/wwayne/react-tooltip/issues/126 that I used [react-tooltip](https://github.com/wwayne/react-tooltip) to display the tooltip when hovering on the Keypad button.

![image](https://cloud.githubusercontent.com/assets/447801/16518930/4ad96a82-3fb8-11e6-8fb1-bab0d73181ca.png)

However,  update react-tooltip to [v3.0.8](https://github.com/wwayne/react-tooltip/releases/tag/3.0.8) still cannot fix this problem when dragging around Axes widget. I will try to find an alternative solution or use a workaround way by removing the react-tooltip component when dragging the Axes widget.

**Comment by cheton** [comment] 2016-07-02 01:41
It's fixed in the master branch, but there is still a minor bug that the Axes widget will lose its original state due to re-rendering widget when dragging from the right pane to the left pane. I may fix it in the later build.

**Comment by cheton** [comment] 2016-07-14 12:15
Fixed in v1.4.0

**Closed by cheton** 2016-07-14 12:15 UTC
Labels: bug
